version: '3'
services: 
  
  app:
    build: .
    environment:
      - FLASK_APP=webtiempo.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork
   
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mynetwork
    
  db:
    image: mongo:latest
    restart: always
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=datostemp
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
        - "27017:27017"
    container_name: db
    networks:
      - mynetwork
    volumes: 
      - mongo_data:/data/db
  
volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge