services: 
  
  miapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      

  web:
    image: nginx:latest
    environment:
     - ALLOW_OVERRIDE=true
    ports:
     - "80:80"
    depends_on:
     - db
    volumes:
     - ./app:/usr/share/ngins/html/
    
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
        - "27017:27017"
    container_name: db
    volumes: 
      - mongo_data: /data/db

