version: '3'
services: 
  
  app:
    build: .
    environment:
      - FLASK_APP=webtiempo.py
    networks:
      - mynetwork
    expose:
      - "5000" 
   
  web:
    image: nginx:latest
    networks:
      - mynetwork
    ports:
      - "80:80"
    volumes:
     - ./nginx.conf/:/etc/nginx/nginx.conf:ro
    
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
        - "27017:27017"
    container_name: db
    volumes: 
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork: