version: '3'
services: 
  
  app:
    build: .
    environment:
      - FLASK_APP=webtiempo.py
      - MONGO_HOST=db
      - MONGO_PORT=27017
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - mynetwork
   
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - mynetwork
    
  
  db:
    image: mongo:latest
    volumes: 
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge