# Utiliza la imagen oficial de Nginx como base
FROM nginx:latest

# Copia tu archivo de configuración al directorio adecuado
RUN mkdir /app
WORKDIR /app
COPY . /app

#COPY ./archivoserver /etc/nginx/sites-available

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]