# Utiliza la imagen oficial de Nginx como base
FROM nginx:latest

# Copia tu archivo de configuración al directorio adecuado
WORKDIR /etc/nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./archivoserver /etc/nginx/sites-available

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]