version: '3'
services: 
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=webtiempo.py
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/entrega/entregadocker
    
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
      MONGO_INITDB_DATABASE: "mydatabase"
    volumes: 
      - mongo_data:/data/db
    
volumes:
  mongo_data:

