apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: mikelpe/as-entrega-api:latest
          env:
            - name: MONGODB_DB
              value: mydatabase
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USERNAME
              value: root
            - name: MONGODB_PASSWORD
              value: example
        
          
          