apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: mikelpe/as-entrega-flask:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: mydatabase
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: root
          - name: MONGODB_PASSWORD
            value: example