apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
      - name: app
        image: mikelpe/as-entrega-docker-imagen:kubeprueba3
        ports:
        - containerPort: 5000
