apiVersion: v1
kind: Service
metadata:
    name: load-balancer
    labels:
        service: load-balancer
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 80
    selector:
        service: nginx
