apiVersion: v1
kind: Service
metadata:
  name: mongo-cluster-ip-service
  labels:
    name: mongo-svc
spec:
  type: ClusterIP
  selector:
    component: mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  