apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - image: mikelpe/nginx-as:1.0.0
          name: nginx
          ports:
            - containerPort: 80
          tty: true
      restartPolicy: Always
