apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webnginx
  template:
    metadata:
      labels:
        component: webnginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
